# This is a basic workflow to help you get started with Actions

name: check code scanning result

# Controls when the workflow will run
on:
  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check_code_scanning_result:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 
     
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          
      - name: Run this repo action.yml, index.js
        run: ./
